export const SEED_COURSES = [
  {
    id: 'c1',
    title: 'Strategic Workforce Planning',
    provider: 'LinkedIn Learning',
    category: 'People Strategy',
    contentType: 'Course',
    format: 'Online',
    duration: '2 hours',
    level: 'Intermediate',
    link: 'https://www.linkedin.com/learning/',
    image: 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=600&h=400&fit=crop',
    description: 'Frameworks for forecasting talent needs and aligning headcount plans with business strategy.',
    reviews: [
      { id: 'r1', name: 'Ploy, Talent Acquisition', rating: 5, comment: 'Very practical, used the framework in our Q3 planning.', date: '2026-05-20' },
      { id: 'r2', name: 'Tum, C&B', rating: 4, comment: 'Good overview, a bit US-centric in the examples.', date: '2026-05-28' },
    ],
  },
  {
    id: 'c2',
    title: 'Cross-Cultural Communication in Asia-Pacific Teams',
    provider: 'Coursera',
    category: 'Communication',
    contentType: 'Video',
    format: 'Self-paced',
    duration: '4 weeks',
    level: 'All levels',
    link: 'https://www.coursera.org/',
    image: 'https://images.unsplash.com/photo-1521737711867-e3b97375f902?w=600&h=400&fit=crop',
    description: 'Practical approaches to working across language, hierarchy, and communication norms in regional teams.',
    reviews: [
      { id: 'r3', name: 'Nick, Marketing TH', rating: 5, comment: 'Great for our regional calls, highly recommend.', date: '2026-06-02' },
    ],
  },
  {
    id: 'c3',
    title: 'Compensation & Benefits Fundamentals',
    provider: 'SHRM',
    category: 'Compensation',
    contentType: 'Course',
    format: 'Online',
    duration: '6 hours',
    level: 'Beginner',
    link: 'https://www.shrm.org/',
    image: 'https://images.unsplash.com/photo-1554224155-8d04cb21cae6?w=600&h=400&fit=crop',
    description: 'Core principles of pay structures, benchmarking, and benefits design for HR practitioners.',
    reviews: [],
  },
];
